package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_shared_library")
load("@makeheaders//rules:makeheaders.bzl", "makeheaders")
load("@libs7//plugin:MACROS.bzl", "s7_plugin", "s7_library")

load("//config/cc:CONFIG.bzl",
     "BASE_SRCS", "BASE_DEPS",
     "BASE_COPTS", "BASE_INCLUDE_PATHS",
     "BASE_DEFINES", "BASE_LINKOPTS")

SRCS = BASE_SRCS
DEPS = BASE_DEPS
INCLUDE_PATHS = BASE_INCLUDE_PATHS
COPTS = BASE_COPTS + INCLUDE_PATHS
DEFINES       = BASE_DEFINES
LINKOPTS      = BASE_LINKOPTS

################################################################
s7_plugin(
    name = "mustachios_s7",
    linkstatic = True,
    alwayslink = True, # ensure init fn sym available for dlsym
    srcs = SRCS + [
        "libmustachios_s7.c",
        ":mkhdrs"
    ],
    hdrs = ["mustachios_s7.h"],
    includes = ["."],
    copts = COPTS,
    deps = DEPS + [
        # mustachios APIs (mustache:render):
        "@mustachios//lib:mustach",
        "@mustachios//adapter/ds_mgr",
        "@mustachios//adapter/json/cjson:mustache_json",
        "@mustachios//adapter/scm/s7:mustache_s7",
        "@mustachios//adapter/toml:mustache_toml",

    ],
    implementation_deps = [
        ## s7 data plugins:
        "@cjson_s7//lib:cjson_s7",
        "@toml_s7//lib:toml_s7",
        "@dune_s7//lib:dune_s7",
    ],
    local_defines = DEFINES,
    linkopts = LINKOPTS
)

cc_shared_library(
    name  = "mustachios_s7_dso",
    shared_lib_name = select({
        "@platforms//os:macos": "libmustachios_s7.dylib",
        "@platforms//os:linux": "libmustachios_s7.so",
        # "@platforms//os:windows": "libmustachios_s7.dll",
        "//conditions:default": "libmustachios_s7.so"
    }),
    deps = [":mustachios_s7"]
)

################################################################
makeheaders(
    name = "mkhdrs",
    hdrs_renamed = {
        "libmustachios_s7.c": "libmustachios_s7_internal.h",
    },
    hdrs_srcs = [],
    additional_srcs = [
        "@liblogc//macros:ansi_colors.h"
    ] + select({
        "@obazl_tools_cc//profile:dev?": [
            "@libs7//macros:s7_logging_debug.h",
            "@liblogc//macros:logging_debug.h"
        ],
        "//conditions:default": [
            "@libs7//macros:s7_logging_ndebug.h",
            "@liblogc//macros:logging_ndebug.h"
        ]
    }),
)

makeheaders(
    name = "export_hdr",
    out  = "mustachios_s7.h",
    export_interface = True,
    hdrs_srcs = [
        "libmustachios_s7.c",
    ],
    additional_srcs = [
        "@liblogc//macros:ansi_colors.h"
    ] + select({
        "@obazl_tools_cc//compilation_mode:fastbuild?": [
            "@libs7//macros:s7_logging_debug.h",
            "@liblogc//macros:logging_debug.h"
        ],
        "//conditions:default": [
            "@libs7//macros:s7_logging_ndebug.h",
            "@liblogc//macros:logging_ndebug.h"
        ]
    }),
)
